[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20.11.1"

# Environment variables (set these in Netlify dashboard):
# VITE_SUPABASE_URL
# VITE_SUPABASE_ANON_KEY
